"use client";

import Header from "@/components/Header/Header";
import "./globals.scss";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { roboto, montserrat } from "@/fonts";
import { availableLocales } from "@/utils/i18n";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return availableLocales.map((locale) => ({
    locale,
  }));
}

export default function RootLayout({ children, params: { locale }, session }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable}`}>
        <SessionProvider session={session}>
          <Header locale={locale} />
          <main>{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
