import { ReactNode } from "react";
import Header from "@/components/Header/Header";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import "./globals.scss";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { roboto, montserrat } from "@/fonts";


interface LayoutProps {
  children?: ReactNode
  params: { locale: "en" | "fr" }
}

export const metadata = {
  title: "MovieApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }: LayoutProps) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable}`}>
        <Header locale={locale} />
        <main>
          <AuthProvider>{children}</AuthProvider>
        </main>
      </body>
    </html>
  );
}